site_name: Blog Tutorial
site_description: an example blog set up following the tutorial
site_url: http://www.example.com

theme:
  name: material
  features:
    - navigation.indexes

plugins:
  - search
  - blog:
      archive_date_format: MM/dd/yyyy
      archive_url_date_format: MM/dd/yyyy
  - meta

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
    - blog/index.md
